personalColor/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('personalColorApp.urls')),
]

personalColorApp/urls.py
from django.urls import path

from personalColorApp import views, result_views

app_name = 'personalColor'
urlpatterns = [
    path('', views.index,name="index"),
    path('picture/',views.picture,name="picture"),
    path('result/',views.result_view,name="result"),
    # path('result/color_2/',result_views.color_2,name="color_2"),
    # path('result/color_3/',result_views.color_3,name="color_3"),
    # path('comment/create/<str:color>',views.create_comment,name="create_comment")
    # # path('/picture/get',views.getPicture,name="getPicture"),
]

personalColorApp/models.py
from django.db import models

# Create your models here.
class Picture(models.Model):
    data = models.ImageField()

class PersonalColor(models.Model):
    color = models.CharField(max_length=100)

class Comment(models.Model):
    color = models.ForeignKey(PersonalColor,on_delete=models.CASCADE)
    contents = models.TextField()
    created_date = models.DateField(auto_created=True)

personalColorApp/forms.py
from django import forms
from .models import Picture, Comment


class PictureForms(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ['data']

class CommentForms(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['contents']

personalColorApp/views.py
from django.utils import timezone

from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from .models import PersonalColor,Comment
import cv2
import numpy as np
from .function import eval


# Create your views here.
def index(request):
    return render(request,"personalColor/index.html")



def picture(request):
    # return render(request, "personalColor/Picture.html")

    if request.method == 'POST':
        image_file = request.FILES['image']
        # image_path = settings.MEDIA_ROOT + '/photos/' + image.name
        # with open(image_path, 'wb') as file:
        #     for chunk in image.chunks():
        #         file.write(chunk)
        #=========================================================

        image_data = image_file.read()

        nparr = np.frombuffer(image_data, np.uint8)

        image = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

        val = eval.perscol(image)
        print(val)
        if val is None:
            return render(request, "personalColor/Picture.html")
        # =========================================================
        data = {"color": val}
        return JsonResponse(data)
    else:
        return render(request, "personalColor/Picture.html")

def result_view(request):
    color = request.GET.get('color')  # 쿼리 매개변수 "color" 가져오기
    # 가져온 "color" 값을 사용하여 필요한 작업 수행
    # ...
    print(color)
    return render(request, 'personalColor/color_1.html', {'color': color})

def create_comment(request,color):

    c = get_object_or_404(PersonalColor, color=color)

    if request.method == "POST":
            comment = Comment(color=c,contents=request.POST["content"],created_date=timezone.now())
            comment.save()
            target = "personalColor:"+c.color
            return redirect(target)

templates/personalColor/Picture.html
<!DOCTYPE html>
<html>
<head>
    <title>Camera Upload</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color:pink;
        }

        #container {
            height: 100vh;
            width: 100vw;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        #video {
            width: auto;
            height: auto;
            max-width: 100%;
            max-height: 100%;
            border: 1px solid #ccc;
        }

        #capture-btn {
            display: block;
            margin-top: 20px;
            padding: 10px 20px;
            font-size: 18px;
            background-color: #fff;
            border: 1px solid #000;
            border-radius: 5px;
            cursor: pointer;
        }


        #canvas {
            display: none;
        }

        #photo {
            width: 100%;
            height: auto;
            display: none;
        }

        @media screen and (max-width: 768px) {
            /* 화면 너비가 768px 이하인 경우 */
            #container {
                padding: 20px;
            }
        }


    </style>
</head>
<body>
    <div id="container">
        <video id="video" autoplay></video>
        <button id="capture-btn">Capture Photo</button>
    </div>



    <canvas id="canvas"></canvas>
    <img id="photo" alt="Captured Photo">

    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        // 웹 카메라에 접근하여 비디오를 표시합니다.
        navigator.mediaDevices.getUserMedia({ video: true })
            .then(function(stream) {
                var video = document.getElementById('video');
                video.srcObject = stream;
            })
            .catch(function(error) {
                console.error('Error accessing the camera.', error);
            });

        // 사진을 찍고 캔버스에 표시합니다.
        document.getElementById('capture-btn').addEventListener('click', function() {
            var video = document.getElementById('video');
            var canvas = document.getElementById('canvas');
            var photo = document.getElementById('photo');

            // 캔버스에 현재 비디오 프레임을 그립니다.
            canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height);

            // 캔버스의 이미지 데이터를 데이터 URL로 변환하여 사진 요소에 표시합니다.
            photo.src = canvas.toDataURL('image/png');

            // 이미지 데이터를 서버에 업로드합니다.
            var formData = new FormData();
            formData.append('image', dataURLtoFile(photo.src, 'photo.png'));

            fetch("{% url 'personalColor:picture' %}", {
                method: 'POST',
                headers: {
                    'X-CSRFToken': getCookie('csrftoken') // CSRF 토큰을 헤더에 포함합니다.
                },
                body: formData
            }).then(function(response) {
                return response.json(); // 서버에서 반환한 데이터를 JSON 형식으로 파싱합니다.
            })
            .then(function(data) {
                var color = data.color;
                var url = "/result?color=" + color;
                // 페이지 리디렉션
                window.location.href = url;

            })
            .catch(function(error) {
                console.error('Error uploading photo.', error);
            });

            console.log(color)
        });

        // 데이터 URL을 파일로 변환합니다.
        function dataURLtoFile(dataURL, filename) {
            var arr = dataURL.split(',');
            var mime = arr[0].match(/:(.*?);/)[1];
            var bstr = atob(arr[1]);
            var n = bstr.length;
            var u8arr = new Uint8Array(n);
            while (n--) {
                u8arr[n] = bstr.charCodeAt(n);
            }
            return new File([u8arr], filename, { type: mime });
        }
    </script>
</body>
</html>

templates/personalColor/color_1.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>{{color}}</h1>
    </div>

</body>
</html>

templates/personalColor/color_2.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>{{color}}</h1>
        <div>
            {% for comment in color.comment_set.all %}
            <div>
                -{{comment.contents}}, {{comment.created_date}}
            </div>
            {%endfor%}
        </div>
        color.color
        <div>
            <form method="post" action="{%url 'personalColor:create_comment' color.color %}">
                {% csrf_token %}
                <textarea name="content"></textarea>
                <button type="submit">Add Comment</button>
            </form>
        </div>
    </div>

</body>
</html>

templates/personalColor/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            background-color: pink;
        }

        form {
            margin-top: 200px;
            text-align: center;
        }

        input[type="submit"] {
            padding: 10px 20px;
            font-size: 18px;
            background-color: white;
            border: 2px solid black;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <form action="{% url 'personalColor:picture' %}" >
        {% csrf_token %}
        <input type="submit" value="실시간 퍼스널컬러 측정">
    </form>
</body>
</html>